"""API Routers."""
from . import (
    parts,
    configurations,
    boms,
    changes,
    documents,
    ipc,
    workflows,
    audit,
    notifications,
    reports,
    integrations,
    requirements,
    suppliers,
    compliance,
    costing,
    service_bulletins,
    projects,
)

__all__ = [
    "parts",
    "configurations",
    "boms",
    "changes",
    "documents",
    "ipc",
    "workflows",
    "audit",
    "notifications",
    "reports",
    "integrations",
    "requirements",
    "suppliers",
    "compliance",
    "costing",
    "service_bulletins",
    "projects",
]
